#AUTOGENERATED! DO NOT EDIT! File to edit: dev/71_audio_model.ipynb (unless otherwise specified).

__all__ = []

#Cell
from ..core import *
from ..torch_basics import *
from ..test import *
from ..data.all import *
from ..callback.fp16 import *
#from local.audio.core import *
from ..notebook.showdoc import *